POST http://localhost:3001/signin
Content-Type: application/json

{
    "email": "bao@gmail.com",
    "password": "123"
}


### Update User
PUT http://localhost:3001/user/update/669fcb36ca1ed23d24a9e4f0
Content-Type: application/json

{
    "username": "giabao123",
    "email": "bao@gmail.com",
    "password": "123"
}